### ISSUE TITLE
issue with installing strain

### ISSUE THREAD

**Issue by malwahedi** [greschd/strain#1]
Hello

I am trying to install Strain module for python (2.7). I have tried to do that using pip:
Pip install strain
I have also used python  3.7:
pip3 install strain
In both cases I got the same following error message:

Collecting strain
  Using cached https://files.pythonhosted.org/packages/4b/66/9800d86638eec760977222640e50daa20f2b2a43e1b8ecc740877d16c6fe/strain-0.2.1.tar.gz
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from strain) (1.16.4)
Requirement already satisfied: fsc.export in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from strain) (1.1.0)
Collecting pymatgen (from strain)
  Using cached https://files.pythonhosted.org/packages/39/c4/adf5b7164e6ec7efc96710a4cf2b068436589b9c44203c9def7e3546e5d6/pymatgen-2019.7.2-cp37-cp37m-macosx_10_7_x86_64.whl
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (0.24.2)
Requirement already satisfied: networkx>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (2.3)
Requirement already satisfied: pydispatcher>=2.0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (2.0.5)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (2.22.0)
Collecting tabulate (from pymatgen->strain)
  Using cached https://files.pythonhosted.org/packages/c2/fd/202954b3f0eb896c53b7b6f07390851b1fd2ca84aa95880d7ae4f434c4ac/tabulate-0.8.3.tar.gz
Requirement already satisfied: matplotlib>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (3.1.1)
Requirement already satisfied: ruamel.yaml>=0.15.6 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (0.15.99)
Collecting spglib>=1.9.9.44 (from pymatgen->strain)
  Using cached https://files.pythonhosted.org/packages/7b/2e/5e49ba47d02d604029358b11d95eebe7c5f859926679e626ed2ba06c3851/spglib-1.13.0.post6.tar.gz
Requirement already satisfied: palettable>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (3.2.0)
Requirement already satisfied: sympy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (1.4)
Collecting monty>=1.0.6 (from pymatgen->strain)
  Using cached https://files.pythonhosted.org/packages/59/dd/668f59ee42d144da2c6194e46d24985a5f62710d8921c0a0532224e47c5b/monty-2.0.4-py3-none-any.whl
Requirement already satisfied: scipy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pymatgen->strain) (1.3.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->pymatgen->strain) (2.8.0)
Requirement already satisfied: pytz>=2011k in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->pymatgen->strain) (2019.1)
Requirement already satisfied: decorator>=4.3.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from networkx>=2.1->pymatgen->strain) (4.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->pymatgen->strain) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->pymatgen->strain) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->pymatgen->strain) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->pymatgen->strain) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=1.5->pymatgen->strain) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=1.5->pymatgen->strain) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib>=1.5->pymatgen->strain) (2.4.0)
Requirement already satisfied: mpmath>=0.19 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sympy->pymatgen->strain) (1.1.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from monty>=1.0.6->pymatgen->strain) (1.12.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5->pymatgen->strain) (41.0.1)
Installing collected packages: tabulate, spglib, monty, pymatgen, strain
  Running setup.py install for tabulate ... done
  Running setup.py install for spglib ... error
    ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/tb/w2lmdhx15cq84zdqydcv8m540000gn/T/pip-install-4p2qmmpn/spglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tb/w2lmdhx15cq84zdqydcv8m540000gn/T/pip-record-llzqs2zv/install-record.txt --single-version-externally-managed --compile:
    ERROR: setuptools is used.
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '1.13.0-6' to '1.13.0.post6'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/spglib
    copying spglib/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/spglib
    copying spglib/spglib.py -> build/lib.macosx-10.9-x86_64-3.7/spglib
    running build_ext
    building 'spglib._spglib' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Isrc -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -c _spglib.c -o build/temp.macosx-10.9-x86_64-3.7/_spglib.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/tb/w2lmdhx15cq84zdqydcv8m540000gn/T/pip-install-4p2qmmpn/spglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tb/w2lmdhx15cq84zdqydcv8m540000gn/T/pip-record-llzqs2zv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/tb/w2lmdhx15cq84zdqydcv8m540000gn/T/pip-install-4p2qmmpn/spglib/

**Comment by greschd** [comment]
Could you please document what fixed the issue for you? It might help someone facing the same problem in the future.

**Comment by malwahedi** [comment]
with python3 I had to install the gcc first and upgrade the setuptools.

**Comment by greschd** [comment]
Thanks!
